num_classes: 2
num_f_maps: 64
num_layers: 10
num_decoders: 3
r1: 2
r2: 2
channel_masking_rate: 0.3
# block_att supports any batch_size; sliding_att requires batch_size=1
att_type: block_att
init_segmentor_path: /code/jjiang23/BalanceTestThesis/initializers/segementor/ASFormer.py
