graph_args: {'layout': 'mp', 'strategy': 'spatial'}
in_channels: 3
dil: [1,2,4,8,16,32,64,128,256,512]
filters: 64
num_joints: 33
init_encoder_path: /code/jjiang23/BalanceTestThesis/initializers/encoder/GCN.py
