config_path: /code/jjiang23/pathml/aim2_balanceV2/models/encoders/MY_SKELETONMAE/pretrain_mae_t120_layer8+5_mask90.yaml
checkpoint_path: /code/jjiang23/pathml/aim2_balanceV2/models/encoders/MAMP/checkpoints/mae-checkpoint.pth
