config_path: /code/jjiang23/pathml/aim2_balanceV2/models/encoders/MY_MAMP/pretrain_mamp_t120_layer8+5_mask90.yaml
checkpoint_path: /data2/pathml/MAMP/checkpoints/checkpoints/ntu120_xset.pth
init_encoder_path: /code/jjiang23/BalanceTestThesis/initializers/encoder/MAMP.py
